import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const canonicalDir = path.join(root, ".superpowers/brainstorm/53164-1785202648/content");
const previewDir = path.join(root, ".superpowers/brainstorm/64526-1785208247/content");

const screens = [
  {no:30,slug:"working-tree",module:"本地 Git",title:"工作区变更",subtitle:"查看未提交文件、状态与本地分支差异",nav:"工作区",layout:"list",primary:"暂存所选",status:"12 个文件 · +286 / −74",items:["SyncCoordinator.swift · 已修改","PermissionRecoveryView.swift · 新文件","GitMate.entitlements · 已修改","README.zh-CN.md · 已修改","LegacyNetworkProbe.swift · 已删除"],side:["main 分支领先远程 3 个提交","2 个文件尚未跟踪","没有检测到冲突","最后自动保存：刚刚"]},
  {no:31,slug:"stage-and-commit",module:"本地 Git",title:"暂存与提交",subtitle:"按文件或代码块暂存，并创建已签名提交",nav:"工作区",layout:"editor",primary:"创建提交",status:"7 个已暂存 · 5 个未暂存",items:["提交标题：修复网络恢复后的重复索引","提交说明支持 Markdown","签名身份：lele · GPG 已验证","提交到分支：fix/local-network-permission"],side:["暂存文件 7","新增行 214","删除行 63","提交前检查通过"]},
  {no:32,slug:"file-diff",module:"本地 Git",title:"文件差异",subtitle:"逐行查看、暂存或放弃单个代码块",nav:"工作区",layout:"console",primary:"暂存此代码块",status:"SyncCoordinator.swift · 4 个代码块",items:["@@ -114,8 +114,14 @@","恢复任务增加幂等标识","网络重新连接后检查现有索引","避免重复创建文件记录","新增回归测试入口"],side:["代码块 1 / 4","+18 / −8","忽略空白变化","并排差异已开启"]},
  {no:33,slug:"stash-manager",module:"本地 Git",title:"Stash 管理",subtitle:"保存、预览、应用和弹出临时工作",nav:"工作区",layout:"list",primary:"新建 Stash",status:"4 个本地 Stash",items:["WIP：网络权限恢复 · 10 分钟前","实验：节点画布自动布局 · 昨天","修复：GHES SSO 回调 · 7 月 26 日","文档：安装与升级说明 · 7 月 22 日","已自动保存的冲突现场 · 7 月 20 日"],side:["包含 8 个文件","基于 fix/local-network-permission","可以无冲突应用","保留未跟踪文件"]},
  {no:34,slug:"merge-rebase-cherry-pick",module:"本地 Git",title:"合并、变基与拣选",subtitle:"可视化选择分支和提交，并预检操作结果",nav:"分支与标签",layout:"canvas",primary:"开始变基",status:"feature/sync → main · 无冲突",items:["main · 5c9d621","feature/sync · 74c2f01","fix/network · a81c32f","release/2.5 · 4e28c1a","选择 3 个提交进行拣选"],side:["预计重放 6 个提交","工作区干净","远程分支已同步","支持中止与继续"]},
  {no:35,slug:"conflict-resolver",module:"本地 Git",title:"冲突解决",subtitle:"三方对比解决合并、变基和拣选冲突",nav:"工作区",layout:"console",primary:"标记为已解决",status:"3 个冲突文件 · 1 个已解决",items:["当前分支：恢复后的索引去重","传入分支：新的同步状态机","最终结果编辑区","采用当前代码块","采用传入代码块"],side:["SyncCoordinator.swift","SyncRecovery.swift","NetworkPermissionView.swift","解决后继续变基"]},
  {no:36,slug:"remotes",module:"本地 Git",title:"远程仓库管理",subtitle:"管理 origin、upstream、推送地址与跟踪关系",nav:"仓库设置",layout:"settings",primary:"添加远程仓库",status:"2 个远程仓库 · 8 个跟踪分支",items:["origin · git@github.com:GitMate/mac-client.git","upstream · https://github.com/open-source/mac-client.git","默认推送：origin","默认拉取：upstream","凭据：GitHub.com · lele"],side:["SSH 连接正常","主机指纹已验证","最近 Fetch：2 分钟前","允许自动清理远程分支"]},
  {no:37,slug:"fetch-pull-push",module:"本地 Git",title:"Fetch、Pull 与 Push",subtitle:"集中查看远程差异和即将执行的同步操作",nav:"工作区",layout:"timeline",primary:"Push 3 个提交",status:"领先 3 · 落后 0",items:["Fetch origin · 已完成","Pull main · 无需更新","Push fix/local-network-permission","远程检查：分支保护通过","上传对象：42 / 42"],side:["传输 1.8 MB","使用 SSH","自动重试已开启","操作日志保留 7 天"]},
  {no:38,slug:"clone-repository",module:"仓库",title:"克隆仓库",subtitle:"从账户、URL 或最近使用列表克隆到本机",nav:"仓库",layout:"wizard",primary:"开始克隆",status:"目标磁盘剩余 182 GB",items:["GitMate/mac-client · 私有 · 2.4 GB","studio/design-system · 私有 · 684 MB","asset-console/web · 公开 · 1.1 GB","粘贴 GitHub 仓库 URL","选择本地保存目录"],side:["克隆方式：完整历史","自动启用同步","Git LFS：自动下载","子模块：递归初始化"]},
  {no:39,slug:"create-repository",module:"仓库",title:"新建仓库",subtitle:"同时创建 GitHub 仓库与本地工作目录",nav:"仓库",layout:"wizard",primary:"创建仓库",status:"账户：lele · GitHub.com",items:["仓库名称：sync-diagnostics","可见性：私有","初始化 README","添加 Swift .gitignore","许可证：MIT"],side:["所有者 lele","默认分支 main","启用议题","启用 Discussions"]},
  {no:40,slug:"import-repository",module:"仓库",title:"导入仓库",subtitle:"从 Git URL 导入并保留完整提交历史",nav:"仓库",layout:"wizard",primary:"开始导入",status:"源仓库连接已验证",items:["源地址：https://git.example.com/tools/client.git","目标：lele/tools-client","导入所有分支与标签","迁移 Git LFS 对象","导入完成后自动克隆"],side:["预计 1.7 GB","24 个分支","18 个标签","凭据仅用于本次导入"]},
  {no:41,slug:"fork-repository",module:"仓库",title:"Fork 仓库",subtitle:"选择所有者、名称、默认分支与本地同步方式",nav:"仓库",layout:"wizard",primary:"创建 Fork",status:"来源：open-source/mac-client",items:["所有者：lele","仓库名称：mac-client","仅复制 main 分支","创建后添加 upstream","创建后自动克隆"],side:["保留来源关系","同步建议已开启","私有 Fork 受组织策略限制","预计占用 2.4 GB"]},
  {no:42,slug:"submodule-lfs",module:"本地 Git",title:"Submodule 与 Git LFS",subtitle:"管理子模块、锁定文件和大文件传输",nav:"仓库设置",layout:"list",primary:"同步全部",status:"3 个子模块 · 128 个 LFS 对象",items:["Vendor/GraphKit · 已同步","Assets/DesignTokens · 落后 2 个提交","Docs/ProductManual · 未初始化","Git LFS：42.8 GB / 50 GB","锁定：AppIcon.fig · lele"],side:["递归更新已开启","LFS 自动拉取已开启","1 个文件被其他用户锁定","配额剩余 7.2 GB"]},
  {no:43,slug:"discussions-overview",module:"Discussions",title:"讨论总览",subtitle:"浏览问答、公告、想法和社区讨论",nav:"讨论",layout:"dashboard",primary:"新建讨论",status:"32 个打开讨论 · 6 个未回答",items:["如何恢复 macOS 本地网络权限？","v2.5 路线与发布时间说明","大型仓库同步性能建议","GHES SSO 配置经验分享","展示你的 GitMate 工作流"],side:["问答 12","公告 4","想法 9","已解决 18"]},
  {no:44,slug:"discussion-detail",module:"Discussions",title:"讨论详情",subtitle:"阅读主题、回复、答案与社区互动",nav:"讨论",layout:"editor",primary:"发布回复",status:"问答 · 已标记答案",items:["问题：网络权限关闭后如何恢复？","lele 回复了排查步骤","yuhan 补充 macOS 15 设置路径","答案已由作者采纳"],side:["7 条回复","3 位参与者","已订阅","分类：问答"]},
  {no:45,slug:"new-discussion",module:"Discussions",title:"新建讨论",subtitle:"选择分类并发布问题、想法或公告",nav:"讨论",layout:"editor",primary:"发布讨论",status:"草稿已保存在本机",items:["分类：想法","标题：支持自定义同步冲突策略","正文：说明使用场景与建议","标签：体验、同步"],side:["允许评论","订阅后续回复","发布身份：lele","社区准则已确认"]},
  {no:46,slug:"actions-overview",module:"Actions",title:"自动化总览",subtitle:"查看工作流状态、运行趋势和失败任务",nav:"Actions",layout:"dashboard",primary:"新建工作流",status:"12 个工作流 · 2 个正在运行",items:["macOS Build · 成功","Release Pipeline · 运行中","CodeQL · 成功","Documentation Preview · 已跳过","Nightly Integration · 失败"],side:["成功率 94.8%","平均耗时 8m 21s","本月 1,284 分钟","3 个失败需要处理"]},
  {no:47,slug:"workflow-detail",module:"Actions",title:"工作流详情与运行历史",subtitle:"查看触发条件、状态、分支和历史运行",nav:"Actions",layout:"list",primary:"运行工作流",status:"macOS Build · 已启用",items:["#1284 · main · 成功 · 8m14s","#1283 · fix/network · 成功 · 7m52s","#1282 · release/2.5 · 失败 · 3m41s","#1281 · main · 成功 · 8m03s","#1280 · main · 已取消 · 1m12s"],side:["触发：push、pull_request","文件：build-and-test.yml","并发限制 2","保留日志 30 天"]},
  {no:48,slug:"workflow-run",module:"Actions",title:"运行日志详情",subtitle:"按任务和步骤查看实时日志、注释与产物",nav:"Actions",layout:"console",primary:"重新运行失败任务",status:"运行 #1282 · 1 个任务失败",items:["设置运行环境 · 成功","签出代码 · 成功","解析依赖 · 成功","构建 GitMate · 失败","上传诊断日志 · 成功"],side:["退出码 65","Xcode 16.0","macOS 14 arm64","错误注释 2"]},
  {no:49,slug:"workflow-dispatch",module:"Actions",title:"手动运行工作流",subtitle:"选择分支、输入参数并确认运行权限",nav:"Actions",layout:"wizard",primary:"运行工作流",status:"Release Pipeline · workflow_dispatch",items:["分支：release/2.5","版本：2.5.0-rc.2","目标：内部测试","是否执行公证：是","是否上传调试符号：是"],side:["预计耗时 18 分钟","需要环境 production","使用 4 个 Secrets","运行者 lele"]},
  {no:50,slug:"artifacts-caches",module:"Actions",title:"构建产物与缓存",subtitle:"下载、保留、删除产物并管理 Actions 缓存",nav:"Actions",layout:"list",primary:"清理过期缓存",status:"42 个产物 · 18.6 GB",items:["GitMate-debug.zip · 42.8 MB","GitMate-dSYM.zip · 18.4 MB","test-results.xcresult · 126 MB","SwiftPM-cache-arm64 · 4.2 GB","Documentation-preview · 84 MB"],side:["缓存命中率 82%","7 天后过期 12 项","本月存储 18.6 GB","可释放 6.4 GB"]},
  {no:51,slug:"releases-overview",module:"Releases",title:"发布版本总览",subtitle:"查看最新发布、草稿、预发布和下载情况",nav:"Releases",layout:"dashboard",primary:"新建发布版本",status:"最新版本 v2.4.0",items:["v2.4.0 · 最新稳定版","v2.5.0-rc.1 · 预发布","v2.3.2 · 安全修复","v2.3.1 · 已弃用","v2.2.0 · 历史版本"],side:["累计下载 18,421","本月下载 3,208","草稿 1","预发布 1"]},
  {no:52,slug:"release-detail",module:"Releases",title:"发布版本详情",subtitle:"查看发行说明、签名、资源与安装命令",nav:"Releases",layout:"editor",primary:"编辑发布版本",status:"v2.4.0 · 已签名 · 最新",items:["GitMate-2.4.0.dmg · 84.2 MB","GitMate-2.4.0.zip · 79.6 MB","Source code (zip)","checksums.txt","release-notes.zh-CN.md"],side:["发布者 lele","标签 v2.4.0","提交 4e28c1a","下载 4,821"]},
  {no:53,slug:"release-editor",module:"Releases",title:"新建与编辑发布版本",subtitle:"选择标签、生成发行说明并上传资源",nav:"Releases",layout:"editor",primary:"发布版本",status:"草稿自动保存在本机",items:["标签：v2.5.0-rc.2","目标分支：release/2.5","标题：GitMate 2.5 RC 2","自动生成发行说明","上传 DMG、ZIP 与校验文件"],side:["标记为预发布","设为最新版本","创建后触发公证","资源签名已验证"]},
  {no:54,slug:"packages-overview",module:"Packages",title:"软件包总览",subtitle:"查看容器、npm、Maven 与其他软件包",nav:"Packages",layout:"dashboard",primary:"连接软件包",status:"6 个软件包 · 24 个版本",items:["ghcr.io/gitmate/sync-service","@gitmate/design-tokens","GitMateCore · Swift Package","gitmate-cli · Homebrew","docs-preview · Container"],side:["本月下载 42,108","存储 12.4 GB","公开 2","私有 4"]},
  {no:55,slug:"package-detail",module:"Packages",title:"软件包版本与权限",subtitle:"管理版本、可见性、仓库连接与下载指令",nav:"Packages",layout:"settings",primary:"复制安装命令",status:"GitMateCore · 2.5.0-rc.2",items:["2.5.0-rc.2 · 最新","2.4.0 · 稳定","2.3.2 · 安全修复","2.3.1 · 已弃用","连接仓库：GitMate/mac-client"],side:["可见性：私有","继承仓库权限","下载 18,204","保留最近 20 个版本"]},
  {no:56,slug:"security-overview",module:"安全",title:"安全中心总览",subtitle:"聚合依赖、代码、密钥与供应链风险",nav:"安全与洞察",layout:"dashboard",primary:"查看安全策略",status:"3 个打开警报 · 0 个严重",items:["Dependabot · 2 个高危","代码扫描 · 1 个中危","密钥扫描 · 0 个","依赖审查 · 已启用","安全策略 SECURITY.md · 已配置"],side:["严重 0","高危 2","中危 1","已修复 28"]},
  {no:57,slug:"dependabot-alerts",module:"安全",title:"Dependabot 警报总览",subtitle:"按严重性、生态和修复状态筛选依赖风险",nav:"安全与洞察",layout:"list",primary:"启用自动修复",status:"8 个打开警报",items:["openssl · 高危 · 可升级","swift-nio · 高危 · 已有修复","marked · 中危 · 可升级","protobuf · 中危 · 暂无修复","sqlite · 低危 · 已忽略"],side:["高危 2","中危 4","低危 2","自动修复 PR 3"]},
  {no:58,slug:"dependabot-detail",module:"安全",title:"Dependabot 警报详情",subtitle:"查看漏洞范围、依赖路径、修复版本与影响",nav:"安全与洞察",layout:"editor",primary:"创建修复拉取请求",status:"CVE-2026-1842 · 高危",items:["受影响：openssl 3.1.0–3.1.4","修复版本：3.1.5","依赖路径：GitMateCore → NetworkKit","CVSS 8.1","没有发现公开利用"],side:["首次发现 2 天前","影响 main 与 release/2.4","自动更新可用","可临时忽略"]},
  {no:59,slug:"code-scanning-alerts",module:"安全",title:"代码扫描警报总览",subtitle:"查看 CodeQL 与第三方扫描工具发现的问题",nav:"安全与洞察",layout:"list",primary:"配置扫描工具",status:"3 个打开警报",items:["不安全的临时文件权限 · 高危","日志中可能包含访问令牌 · 中危","未验证的 URL Scheme · 中危","弱随机数生成 · 已修复","路径遍历 · 已忽略"],side:["CodeQL 2","Semgrep 1","高危 1","修复中 2"]},
  {no:60,slug:"code-scanning-detail",module:"安全",title:"代码扫描警报详情",subtitle:"定位数据流、代码路径、分支和修复建议",nav:"安全与洞察",layout:"console",primary:"创建修复分支",status:"日志中可能包含访问令牌 · 中危",items:["来源：OAuthCallbackHandler.swift:84","传播：AuthLogger.swift:42","汇点：OSLog.info","影响分支：main、release/2.4","建议：使用 privacy: .private"],side:["规则 swift/sensitive-log","精度：高","首次发现 6 小时前","1 个相关路径"]},
  {no:61,slug:"secret-scanning",module:"安全",title:"密钥扫描",subtitle:"查看泄露凭据、推送保护和撤销状态",nav:"安全与洞察",layout:"list",primary:"配置推送保护",status:"1 个需要处理的警报",items:["GitHub Personal Access Token · 有效","AWS Access Key · 已撤销","Slack Webhook · 已解决","测试凭据 · 已标记为测试","推送保护绕过请求 · 0"],side:["推送保护已开启","合作伙伴验证已开启","有效密钥 1","平均解决时间 18 分钟"]},
  {no:62,slug:"dependency-graph",module:"安全",title:"依赖关系图与 SBOM",subtitle:"可视化直接、间接依赖与许可证风险",nav:"安全与洞察",layout:"canvas",primary:"导出 SBOM",status:"128 个依赖 · 9 个生态",items:["GitMateCore","NetworkKit","swift-nio","openssl","SQLite.swift"],side:["直接依赖 24","间接依赖 104","许可证风险 2","CycloneDX / SPDX"]},
  {no:63,slug:"insights-overview",module:"洞察",title:"仓库洞察总览",subtitle:"汇总活跃度、协作效率、代码健康和发布趋势",nav:"安全与洞察",layout:"dashboard",primary:"导出报告",status:"统计周期：最近 30 天",items:["提交 286 · +18%","拉取请求 42 · +8%","议题关闭 31 · +12%","平均审核 4.2 小时","发布 3 个版本"],side:["活跃贡献者 8","首次响应 38 分钟","构建成功率 94.8%","安全修复 6"]},
  {no:64,slug:"traffic-contributors",module:"洞察",title:"流量、提交与贡献者",subtitle:"查看访问来源、克隆、提交频率和贡献分布",nav:"安全与洞察",layout:"timeline",primary:"切换统计周期",status:"最近 14 天 · 1,842 次查看",items:["独立访问者 628","完整克隆 142","热门路径 /docs/sync-recovery","lele · 84 次提交","yuhan · 37 次提交"],side:["GitHub 搜索 42%","直接访问 31%","文档链接 18%","其他 9%"]},
  {no:65,slug:"network-forks",module:"洞察",title:"网络、Fork 与活动",subtitle:"查看仓库网络关系、Fork 同步和事件时间线",nav:"安全与洞察",layout:"canvas",primary:"查看完整网络",status:"12 个 Fork · 4 个活跃",items:["GitMate/mac-client · 主仓库","lele/mac-client · 领先 2","studio/mac-client · 落后 18","enterprise/mac-client · 私有 Fork","合并请求来源 6"],side:["本周 Fork 2","活跃分支 16","未同步 Fork 3","网络深度 2"]},
  {no:66,slug:"repository-general-settings",module:"仓库设置",title:"常规设置",subtitle:"管理仓库名称、描述、可见性与功能开关",nav:"仓库设置",layout:"settings",primary:"保存更改",status:"GitMate/mac-client · 私有",items:["仓库名称与描述","默认分支 main","议题与 Discussions","合并策略","自动关闭已合并分支"],side:["拥有者 GitMate","创建于 2024 年","磁盘 2.4 GB","规则集 3"]},
  {no:67,slug:"repository-access",module:"仓库设置",title:"协作者与访问权限",subtitle:"管理直接访问、团队角色和待处理邀请",nav:"仓库设置",layout:"list",primary:"添加协作者",status:"6 个具有访问权限的主体",items:["lele · 管理员","yuhan · 维护","design-team · 写入","security-team · 分类","mingxu · 待接受邀请"],side:["管理员 1","维护 1","写入 2","外部协作者 2"]},
  {no:68,slug:"webhooks",module:"仓库设置",title:"Webhook",subtitle:"管理事件订阅、签名密钥和投递记录",nav:"仓库设置",layout:"list",primary:"添加 Webhook",status:"3 个 Webhook · 2 个正常",items:["ci.example.com/github · 正常","deploy.gitmate.dev/hook · 正常","legacy.example.com · 最近失败","最近投递 #91842 · 200","重新投递失败事件"],side:["事件 push、pull_request","内容 JSON","SSL 验证开启","平均响应 284ms"]},
  {no:69,slug:"environments",module:"仓库设置",title:"部署环境",subtitle:"配置保护规则、审核者、分支策略与环境 Secrets",nav:"仓库设置",layout:"settings",primary:"新建环境",status:"3 个环境",items:["production · 需要审核","staging · 自动部署","preview · 动态环境","分支策略：release/*","等待计时器：5 分钟"],side:["部署审核者 2","环境 Secrets 8","保护分支 3","最近部署成功"]},
  {no:70,slug:"secrets-variables",module:"仓库设置",title:"Secrets 与变量",subtitle:"管理 Actions、Codespaces 与 Dependabot 配置值",nav:"仓库设置",layout:"settings",primary:"新建 Secret",status:"12 个 Secrets · 8 个变量",items:["APPLE_NOTARY_PASSWORD · 2 天前更新","SENTRY_AUTH_TOKEN · 18 天前更新","GHES_TEST_TOKEN · 30 天前更新","RELEASE_CHANNEL · production","CACHE_VERSION · v4"],side:["Actions 14","Codespaces 3","Dependabot 3","所有值已加密"]},
  {no:71,slug:"deploy-keys-apps",module:"仓库设置",title:"Deploy Keys 与 GitHub Apps",subtitle:"管理机器密钥、已安装应用和仓库授权",nav:"仓库设置",layout:"list",primary:"添加 Deploy Key",status:"2 个密钥 · 4 个应用",items:["Production deploy key · 只读","Staging deploy key · 可写","Sentry · 读议题与提交","Codecov · 读检查","Dependabot · 依赖更新"],side:["过期密钥 0","最近使用 4 分钟前","写入密钥 1","已验证应用 4"]},
  {no:72,slug:"github-pages",module:"仓库设置",title:"GitHub Pages",subtitle:"配置构建来源、自定义域名和 HTTPS",nav:"仓库设置",layout:"settings",primary:"保存 Pages 设置",status:"站点已发布",items:["来源：GitHub Actions","地址：https://docs.gitmate.dev","自定义域名已验证","强制 HTTPS 已开启","最近部署 6 分钟前"],side:["状态：正常","证书有效","构建 1m 42s","访问 842 / 天"]},
  {no:73,slug:"actions-settings",module:"仓库设置",title:"Actions 策略",subtitle:"限制工作流权限、Fork 行为、制品与日志保留",nav:"仓库设置",layout:"settings",primary:"保存 Actions 策略",status:"继承组织策略并有 2 项覆盖",items:["允许 GitHub 与已验证 Actions","默认令牌权限：只读","Fork 工作流需要批准","产物保留 30 天","缓存保留 7 天"],side:["允许列表 18","阻止 Actions 2","并发任务 10","月配额 3,000 分钟"]},
  {no:74,slug:"repository-danger-zone",module:"仓库设置",title:"转移、归档与删除仓库",subtitle:"集中处理需要强确认的仓库级危险操作",nav:"仓库设置",layout:"state",primary:"打开危险操作",status:"所有操作默认锁定",items:["转移仓库所有权","将仓库设为只读归档","解除仓库归档","删除仓库及所有数据","更改仓库可见性"],side:["要求重新验证身份","显示影响范围","必须输入完整仓库名","支持倒计时取消"]},
  {no:75,slug:"organization-overview",module:"组织与企业",title:"组织总览",subtitle:"查看组织仓库、成员、安全和使用情况",nav:"组织",layout:"dashboard",primary:"组织设置",status:"GitMate · 28 个仓库",items:["活跃仓库 18","成员 42","团队 7","安全警报 12","Actions 使用 68%"],side:["所有者 3","外部协作者 6","私有仓库 24","企业策略正常"]},
  {no:76,slug:"organization-members",module:"组织与企业",title:"组织成员",subtitle:"管理成员角色、邀请、外部协作者和 2FA 状态",nav:"组织",layout:"list",primary:"邀请成员",status:"42 个成员 · 2 个待接受",items:["lele · 所有者 · 2FA","yuhan · 成员 · 2FA","mingxu · 成员 · 2FA","external-ci · 外部协作者","new-user · 待接受邀请"],side:["所有者 3","成员 39","外部协作者 6","2FA 覆盖 100%"]},
  {no:77,slug:"organization-teams",module:"组织与企业",title:"团队与权限",subtitle:"管理团队层级、成员和仓库访问角色",nav:"组织",layout:"list",primary:"新建团队",status:"7 个团队",items:["Core · 维护 8 个仓库","Security · 分类 28 个仓库","Design · 写入 4 个仓库","Release · 维护 6 个仓库","Docs · 写入 9 个仓库"],side:["父子团队 3 层","成员 42","仓库授权 55","IdP 同步 4 个团队"]},
  {no:78,slug:"organization-repositories",module:"组织与企业",title:"组织仓库与角色",subtitle:"批量查看可见性、归档状态、团队权限和规则继承",nav:"组织",layout:"list",primary:"新建组织仓库",status:"28 个仓库",items:["mac-client · 私有 · Core 维护","sync-service · 私有 · Platform 管理","design-system · 内部 · Design 写入","docs · 公开 · Docs 维护","legacy-client · 已归档"],side:["私有 20","内部 4","公开 4","已归档 3"]},
  {no:79,slug:"enterprise-audit",module:"组织与企业",title:"企业策略与审计日志",subtitle:"检查企业级策略、身份、安全事件和导出记录",nav:"组织",layout:"timeline",primary:"导出审计日志",status:"GHES · 策略同步正常",items:["repo.access 角色变更","org.invite 成员邀请","secret_scanning.alert 解决","workflow.run 手动触发","sso.login 企业身份验证"],side:["日志保留 180 天","SAML SSO 已强制","IP 允许列表已开启","流式导出正常"]},
  {no:80,slug:"accounts",module:"全局设置",title:"GitHub 账户管理",subtitle:"管理 GitHub.com 与多个 GHES 账户边界",nav:"设置",layout:"settings",primary:"添加账户",status:"3 个账户 · 全部在线",items:["lele · GitHub.com · 当前","lele-enterprise · github.company.com","release-bot · GHES · 受限","账户隔离与默认身份","重新授权与移除账户"],side:["默认账户 GitHub.com","企业数据独立存储","令牌存于钥匙串","最后验证刚刚"]},
  {no:81,slug:"sync-storage",module:"全局设置",title:"同步与本地存储",subtitle:"配置自动同步、带宽、缓存和磁盘占用",nav:"设置",layout:"settings",primary:"立即清理缓存",status:"18 个仓库 · 24.8 GB",items:["自动同步：开启","仅 Wi‑Fi 下载 LFS","索引并发：4","缓存上限：30 GB","日志保留：14 天"],side:["仓库数据 19.6 GB","LFS 缓存 3.8 GB","索引 1.1 GB","可清理 4.2 GB"]},
  {no:82,slug:"appearance-language-shortcuts",module:"全局设置",title:"外观、语言与快捷键",subtitle:"配置主题、字号、密度、语言和全局快捷键",nav:"设置",layout:"settings",primary:"恢复默认",status:"白色主题 · 简体中文",items:["主题：白色","文字大小：标准","界面密度：舒适","语言：简体中文","命令面板：⌘K"],side:["跟随系统强调色","减少动画：关闭","高对比度：开启","快捷键冲突 0"]},
  {no:83,slug:"global-search",module:"全局工具",title:"全局搜索与命令面板",subtitle:"跨账户搜索仓库、代码、议题、PR 与命令",nav:"搜索",layout:"list",primary:"打开高级搜索",status:"⌘K · 搜索“network recovery”",items:["代码 · SyncRecovery.swift","议题 #91 · 本地网络权限提示","拉取请求 #214 · 恢复入口","仓库 · GitMate/mac-client","命令 · Fetch 所有仓库"],side:["范围：全部账户","最近搜索 8","保存的搜索 4","支持 GitHub 语法"]},
  {no:84,slug:"diagnostics-update-about",module:"全局设置",title:"诊断、更新与关于",subtitle:"查看版本、更新状态、日志和运行环境",nav:"设置",layout:"settings",primary:"检查更新",status:"GitMate 2.5.0 · 最新",items:["更新通道：稳定版","自动下载更新","导出诊断包","打开日志目录","隐私与开源许可"],side:["macOS 15.0","Apple Silicon","Git 2.46.0","数据库状态正常"]},
  {no:85,slug:"gists-overview",module:"Gists",title:"Gist 总览",subtitle:"查看私密、公开、已加星和最近更新的 Gist",nav:"Gists",layout:"dashboard",primary:"新建 Gist",status:"18 个 Gist",items:["network-diagnostics.sh · 私密","swift-concurrency-notes.md · 公开","release-checklist.md · 私密","ghes-sso-debug.txt · 私密","git-recovery-commands.md · 已加星"],side:["私密 12","公开 6","已加星 9","Fork 4"]},
  {no:86,slug:"gist-editor",module:"Gists",title:"Gist 查看与编辑",subtitle:"管理多文件 Gist、版本、评论与可见性",nav:"Gists",layout:"editor",primary:"保存新版本",status:"network-diagnostics.sh · 私密",items:["network-diagnostics.sh","README.md","版本 8 · 2 天前","3 条评论","Fork 2"],side:["所有者 lele","文件 2","可见性：私密","支持克隆 URL"]},
  {no:87,slug:"wiki-overview",module:"Wiki",title:"Wiki 总览",subtitle:"浏览页面树、最近更新和仓库文档导航",nav:"介绍",layout:"list",primary:"新建 Wiki 页面",status:"24 个页面",items:["Home","安装与升级","同步与网络恢复","Enterprise SSO","故障排查"],side:["最近更新 6","贡献者 4","克隆地址可用","页面历史已开启"]},
  {no:88,slug:"wiki-editor",module:"Wiki",title:"Wiki 查看与编辑",subtitle:"Markdown 编辑、预览、页面历史和侧边栏管理",nav:"介绍",layout:"editor",primary:"保存页面",status:"同步与网络恢复 · 草稿已保存",items:["正文 Markdown 编辑器","页面摘要","自定义侧边栏","页脚链接","版本差异与恢复"],side:["最后编辑 lele","12 个修订版本","链接检查通过","提交消息已填写"]},
  {no:89,slug:"permission-rate-limit-states",module:"异常状态",title:"权限不足与 API 限流",subtitle:"统一展示授权缺失、组织策略阻止与速率限制恢复",nav:"状态中心",layout:"state",primary:"重新授权",status:"异常状态设计集合",items:["缺少仓库写入权限","组织策略禁止操作","SAML SSO 需要重新验证","REST API 速率限制","GraphQL 查询成本过高"],side:["明确受影响操作","显示恢复时间","保留未提交输入","提供诊断详情"]},
  {no:90,slug:"offline-sync-conflict-states",module:"异常状态",title:"离线、同步冲突与网络恢复",subtitle:"覆盖断网、代理失败、数据冲突和自动续传状态",nav:"状态中心",layout:"state",primary:"重试全部",status:"网络异常设计集合",items:["当前处于离线模式","同步中网络中断","本地与远程记录冲突","代理或证书验证失败","连接恢复后自动续传"],side:["不丢失本地操作","实时显示正在处理的文件","长条进度条","错误可单项重试"]},
  {no:91,slug:"danger-progress-center",module:"通用流程",title:"危险操作确认与任务进度中心",subtitle:"统一承载删除、强制推送、重写历史和长任务",nav:"状态中心",layout:"state",primary:"打开任务中心",status:"通用交互设计集合",items:["强制推送二次确认","删除分支与标签","删除仓库永久确认","导入、克隆与迁移进度","后台任务完成通知"],side:["显示精确影响范围","要求输入目标名称","支持安全取消","保留可恢复日志"]}
];

const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({
  "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"
}[char]));

const layoutNames = {
  dashboard:"概览仪表盘",list:"列表与详情",editor:"编辑与设置",console:"步骤与日志",
  settings:"设置管理",canvas:"可视化画布",timeline:"时间线",wizard:"向导",state:"状态集合"
};

const commonCss = `
<style>
  .batch-page-meta{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:0 0 12px}
  .batch-page-index{display:inline-flex;padding:6px 9px;border-radius:999px;color:#1f6eb8;background:#e9f3fc;font-size:11px;font-weight:800}
  .batch-page-status{color:#465366;font-size:11px;font-weight:650}
  .batch-app{height:680px;overflow:hidden;border:1px solid #c8ced7;border-radius:15px;color:#172033;background:#fff;box-shadow:0 22px 55px rgba(32,42,58,.16)}
  .batch-app *{box-sizing:border-box}.batch-titlebar{position:relative;display:flex;height:42px;padding:0 14px;align-items:center;justify-content:space-between;border-bottom:1px solid #dfe4ea;background:#fff}
  .batch-traffic{display:flex;gap:7px}.batch-traffic i{width:11px;height:11px;border-radius:50%}.batch-traffic i:nth-child(1){background:#ff5f57}.batch-traffic i:nth-child(2){background:#febc2e}.batch-traffic i:nth-child(3){background:#28c840}
  .batch-window-title{position:absolute;left:50%;transform:translateX(-50%);color:#465366;font-size:10px;font-weight:700}.batch-tools{display:flex;gap:7px}.batch-tool{display:grid;width:25px;height:25px;place-items:center;border:1px solid #d9dfe7;border-radius:7px;color:#647187;background:#fff;font-size:10px}
  .batch-body{display:grid;height:calc(100% - 42px);grid-template-columns:176px minmax(0,1fr)}.batch-sidebar{display:flex;min-height:0;padding:13px 10px 11px;flex-direction:column;border-right:1px solid #dfe4ea;background:#f1f4f7}
  .batch-brand{display:flex;margin:0 6px 12px;gap:8px;align-items:center}.batch-avatar{width:29px;height:29px;flex:0 0 auto;border:2px solid #fff;border-radius:50%;background:radial-gradient(circle at 50% 32%,#ddb18e 0 18%,transparent 19%),radial-gradient(circle at 50% 92%,#426b91 0 39%,transparent 40%),linear-gradient(145deg,#e7eef5,#9fb5c8);box-shadow:0 0 0 1px #c9d7e2}.batch-brand b{display:block;color:#1d2737;font-size:10px}.batch-brand span{display:block;margin-top:2px;color:#536174;font-size:6px;font-weight:600}
  .batch-repo{display:grid;height:39px;margin:0 2px 11px;padding:0 7px;grid-template-columns:25px 1fr auto;gap:7px;align-items:center;border:1px solid #d6dde5;border-radius:8px;background:#fff}.batch-repo-icon{display:grid;width:24px;height:24px;place-items:center;border-radius:7px;color:#fff;background:linear-gradient(145deg,#438fd9,#276db8);font-size:6px;font-weight:800}.batch-repo b{display:block;overflow:hidden;color:#223047;font-size:6px;text-overflow:ellipsis;white-space:nowrap}.batch-repo small{display:block;margin-top:2px;color:#596779;font-size:5px}
  .batch-nav-group{margin-bottom:8px}.batch-nav-label{margin:0 8px 4px;color:#657386;font-size:5px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.batch-nav-item{display:grid;height:27px;padding:0 8px;grid-template-columns:17px 1fr auto;gap:5px;align-items:center;border-radius:7px;color:#344054;font-size:7px;font-weight:650}.batch-nav-item i{color:#526174;font-style:normal;font-size:8px}.batch-nav-item.active{color:#195fa8;background:#dceafa}.batch-nav-item.active i{color:#2879ca}.batch-badge{min-width:16px;padding:2px 4px;border-radius:99px;color:#445166;background:#dfe4ea;text-align:center;font-size:5px}.batch-sidebar-bottom{margin-top:auto}.batch-sync{display:flex;margin:0 4px 7px;padding:7px;gap:6px;align-items:center;border:1px solid #d9dfe6;border-radius:8px;background:#fff}.batch-sync i{width:7px;height:7px;border:2px solid #67aa70;border-radius:50%;box-shadow:0 0 0 2px #dceedd}.batch-sync b{display:block;color:#273447;font-size:6px}.batch-sync span{display:block;margin-top:2px;color:#536174;font-size:5px}
  .batch-main{display:grid;min-width:0;min-height:0;padding:13px 15px 12px;grid-template-rows:50px 68px minmax(0,1fr);gap:9px;background:#f7f9fb}.batch-head{display:flex;min-width:0;align-items:flex-start;justify-content:space-between}.batch-head h1{margin:0 0 5px;color:#172033;font-size:17px;letter-spacing:-.03em}.batch-head p{margin:0;color:#536174;font-size:7px;font-weight:550}.batch-actions{display:flex;gap:7px;align-items:center}.batch-status{display:flex;height:29px;padding:0 8px;gap:5px;align-items:center;border:1px solid #d7dee6;border-radius:7px;color:#536174;background:#fff;font-size:6px;font-weight:650}.batch-status i{width:6px;height:6px;border-radius:50%;background:#4b965e}.batch-primary{display:grid;height:29px;padding:0 10px;place-items:center;border-radius:7px;color:#fff;background:#2f7fd2;box-shadow:0 4px 11px rgba(39,104,172,.15);font-size:7px;font-weight:750}
  .batch-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.batch-metric{display:grid;padding:8px 10px;grid-template-columns:1fr auto;align-items:center;border:1px solid #dfe4ea;border-radius:9px;background:#fff}.batch-metric span{display:block;color:#536174;font-size:6px;font-weight:600}.batch-metric b{display:block;margin-top:3px;color:#1d2a3d;font-size:11px}.batch-metric i{display:grid;width:27px;height:27px;place-items:center;border-radius:8px;color:#3479bd;background:#e8f3fc;font-style:normal;font-size:8px}
  .batch-content{position:relative;display:grid;min-width:0;min-height:0;gap:10px}.batch-layout-list,.batch-layout-settings{grid-template-columns:minmax(0,1.35fr) minmax(275px,.65fr)}.batch-layout-editor{grid-template-columns:minmax(0,1fr) 285px}.batch-layout-console{grid-template-columns:230px minmax(0,1fr)}.batch-layout-dashboard{grid-template-columns:minmax(0,1.45fr) 275px}.batch-layout-wizard{grid-template-columns:minmax(0,1fr) 300px}.batch-layout-canvas,.batch-layout-timeline,.batch-layout-state{grid-template-columns:minmax(0,1fr)}
  .batch-panel{display:flex;min-width:0;min-height:0;flex-direction:column;overflow:hidden;border:1px solid #dce2e9;border-radius:10px;background:#fff;box-shadow:0 2px 7px rgba(33,47,66,.035)}.batch-panel.focus{border-color:#c4dcf0;box-shadow:0 8px 20px rgba(43,92,142,.08)}.batch-panel-head{display:flex;height:38px;flex:0 0 auto;padding:0 10px;align-items:center;justify-content:space-between;border-bottom:1px solid #e7ebf0;background:#fafbfd}.batch-panel-head b{color:#263247;font-size:8px}.batch-panel-head span{color:#3976b1;font-size:6px;font-weight:700}.batch-scroll{min-height:0;flex:1;overflow:auto}.batch-row{position:relative;display:grid;min-height:55px;padding:8px 10px;grid-template-columns:25px minmax(0,1fr) auto;gap:8px;align-items:center;border-bottom:1px solid #edf0f3}.batch-row.selected{background:#edf6fe}.batch-row.selected:before{position:absolute;inset:7px auto 7px 0;width:3px;border-radius:0 3px 3px 0;background:#2f7fd2;content:""}.batch-row-icon{display:grid;width:24px;height:24px;place-items:center;border-radius:7px;color:#3475b2;background:#eaf3fb;font-size:7px;font-weight:800}.batch-row b{display:block;margin-bottom:4px;color:#334155;font-size:7px}.batch-row p{margin:0;color:#596779;font-size:5px;font-weight:550}.batch-row-tag{padding:4px 6px;border-radius:6px;color:#39794a;background:#eaf7ee;font-size:5px;font-weight:750}
  .batch-detail{padding:11px}.batch-detail h2{margin:0 0 7px;color:#172337;font-size:11px}.batch-detail p{margin:0 0 10px;color:#536174;font-size:6px;font-weight:550;line-height:1.55}.batch-detail-card{padding:8px;border:1px solid #e0e5eb;border-radius:7px;background:#fafbfd}.batch-detail-card+.batch-detail-card{margin-top:7px}.batch-detail-card span{display:block;color:#657386;font-size:5px}.batch-detail-card b{display:block;margin-top:4px;color:#263247;font-size:7px}
  .batch-editor{min-height:0;padding:10px;overflow:auto}.batch-input{display:flex;height:34px;padding:0 9px;align-items:center;border:1px solid #cfd8e1;border-radius:7px;color:#243247;background:#fff;font-size:7px;font-weight:650}.batch-editor-box{margin-top:9px;overflow:hidden;border:1px solid #d5dce4;border-radius:8px}.batch-editor-toolbar{display:flex;height:30px;padding:0 7px;gap:5px;align-items:center;border-bottom:1px solid #e5eaf0;background:#fafbfd;color:#536174;font-size:6px;font-weight:700}.batch-editor-body{min-height:190px;padding:11px;color:#344054;background:linear-gradient(#f2f5f8 1px,transparent 1px);background-size:100% 24px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:6px;line-height:1.75}.batch-footer{display:flex;height:43px;flex:0 0 auto;padding:0 10px;gap:7px;align-items:center;border-top:1px solid #e5eaf0;background:#fafbfd;color:#536174;font-size:5px;font-weight:650}.batch-footer span:last-child{margin-left:auto;color:#3976b1;font-weight:750}
  .batch-console{min-height:0;padding:9px;overflow:auto;background:#f8fafc;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:5.5px;line-height:1.65}.batch-code-line{display:grid;grid-template-columns:30px minmax(0,1fr);gap:8px;padding:2px 4px;color:#405064}.batch-code-line span:first-child{color:#8a96a5;text-align:right}.batch-code-line.good span:last-child{color:#39794a}.batch-code-line.bad span:last-child{color:#a34d57}.batch-code-line.command span:last-child{color:#286aa9}
  .batch-setting{display:grid;min-height:58px;padding:9px 10px;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;border-bottom:1px solid #edf0f3}.batch-setting b{display:block;margin-bottom:4px;color:#334155;font-size:7px}.batch-setting p{margin:0;color:#596779;font-size:5px;font-weight:550}.batch-toggle{width:27px;height:16px;padding:2px;border-radius:99px;background:#4b965e}.batch-toggle:after{display:block;width:12px;height:12px;margin-left:auto;border-radius:50%;background:#fff;content:""}
  .batch-canvas{position:relative;min-height:0;flex:1;overflow:auto;background:linear-gradient(#edf1f5 1px,transparent 1px),linear-gradient(90deg,#edf1f5 1px,transparent 1px),#fbfcfd;background-size:25px 25px}.batch-lanes{display:grid;min-width:900px;min-height:100%;padding:16px;grid-template-columns:repeat(4,1fr);gap:11px}.batch-lane{padding:8px;border:1px solid #dfe4ea;border-radius:9px;background:rgba(255,255,255,.92)}.batch-lane h3{display:flex;margin:0 0 9px;align-items:center;justify-content:space-between;color:#334155;font-size:7px}.batch-node{margin-bottom:7px;padding:8px;border:1px solid #dce3e9;border-radius:8px;background:#fff;box-shadow:0 2px 5px rgba(34,48,67,.04)}.batch-node b{display:block;margin-bottom:4px;color:#273548;font-size:6px}.batch-node span{color:#596779;font-size:5px;font-weight:550}.batch-timeline{position:relative;min-height:0;flex:1;padding:12px 18px 18px 78px;overflow:auto}.batch-timeline:before{position:absolute;top:20px;bottom:20px;left:49px;width:2px;background:#d7e0e8;content:""}.batch-event{position:relative;margin-bottom:9px;padding:9px 10px;border:1px solid #dfe4ea;border-radius:8px;background:#fff}.batch-event:before{position:absolute;top:13px;left:-35px;width:9px;height:9px;border:2px solid #fff;border-radius:50%;background:#2f7fd2;box-shadow:0 0 0 2px #a9cae8;content:""}.batch-event b{display:block;margin-bottom:4px;color:#334155;font-size:7px}.batch-event span{color:#596779;font-size:5px;font-weight:550}
  .batch-state-grid{display:grid;min-height:0;padding:10px;grid-template-columns:1fr 1fr;gap:9px;overflow:auto}.batch-state-card{position:relative;padding:11px;border:1px solid #dfe4ea;border-radius:9px;background:#fff}.batch-state-card.warning{border-color:#efd7b4;background:#fffaf2}.batch-state-card.danger{border-color:#edcbd0;background:#fff8f9}.batch-state-card h3{margin:0 0 6px;color:#263247;font-size:8px}.batch-state-card p{margin:0 0 8px;color:#596779;font-size:6px;font-weight:550;line-height:1.5}.batch-state-action{display:inline-flex;padding:5px 7px;border-radius:6px;color:#fff;background:#2f7fd2;font-size:5px;font-weight:750}.batch-state-card.danger .batch-state-action{background:#b74d58}
  .batch-entry{margin-bottom:28px;scroll-margin-top:12px}.batch-index{margin-bottom:22px;padding:16px;border:1px solid #ccd6e0;border-radius:14px;background:#fff;box-shadow:0 12px 32px rgba(32,42,58,.10)}.batch-index h1{margin:0 0 6px;color:#172033;font-size:22px}.batch-index p{margin:0;color:#536174;font-size:12px}.batch-index-grid{display:grid;margin-top:14px;grid-template-columns:repeat(4,1fr);gap:8px}.batch-index-card{display:block;padding:10px;border:1px solid #dfe4ea;border-radius:9px;color:#263247;background:#fafbfd;text-decoration:none}.batch-index-card span{display:block;color:#3976b1;font-size:9px;font-weight:800}.batch-index-card b{display:block;margin-top:4px;font-size:11px}.batch-index-card small{display:block;margin-top:4px;color:#657386;font-size:9px}
  @media(max-width:960px){.batch-app{height:640px}.batch-body{grid-template-columns:155px minmax(0,1fr)}.batch-main{padding:11px 12px 10px}.batch-layout-list,.batch-layout-settings,.batch-layout-dashboard{grid-template-columns:minmax(0,1fr) 250px}.batch-index-grid{grid-template-columns:repeat(3,1fr)}}
</style>`;

function navHtml(active) {
  const groups = [
    ["仓库", [["⌂","仓库"],["◫","工作区"],["⌘","文件与提交"],["⑂","分支与标签"]]],
    ["协作", [["○","议题"],["⇄","拉取请求"],["◉","讨论"]]],
    ["发布与运行", [["▶","Actions"],["◇","Releases"],["□","Packages"]]],
    ["管理", [["⌾","安全与洞察"],["⚙","仓库设置"],["◎","组织"],["⌕","搜索"],["⚙","设置"]]]
  ];
  return groups.map(([label, items]) => `<div class="batch-nav-group"><div class="batch-nav-label">${label}</div>${items.map(([icon,name]) => `<div class="batch-nav-item${active.includes(name) ? " active" : ""}"><i>${icon}</i><span>${name}</span>${["议题","拉取请求"].includes(name) ? `<span class="batch-badge">${name==="议题"?"8":"7"}</span>`:""}</div>`).join("")}</div>`).join("");
}

function metrics(screen) {
  const values = [
    ["当前状态",screen.status],
    ["页面类型",layoutNames[screen.layout]],
    ["账户","lele · GitHub.com"],
    ["同步","刚刚完成"]
  ];
  return `<section class="batch-metrics">${values.map((v,i)=>`<div class="batch-metric"><div><span>${esc(v[0])}</span><b>${esc(v[1])}</b></div><i>${["●","▦","◎","↻"][i]}</i></div>`).join("")}</section>`;
}

function rows(items) {
  return items.map((item,index)=>`<div class="batch-row${index===0?" selected":""}"><span class="batch-row-icon">${String(index+1).padStart(2,"0")}</span><div><b>${esc(item)}</b><p>GitMate/mac-client · ${index===0?"刚刚更新":`${index+2} 小时前`}</p></div><span class="batch-row-tag">${index===0?"当前":"正常"}</span></div>`).join("");
}

function sideCards(items) {
  return items.map((item,index)=>`<div class="batch-detail-card"><span>${["状态","范围","策略","说明"][index%4]}</span><b>${esc(item)}</b></div>`).join("");
}

function consoleLines(items) {
  const base = ["准备运行环境","读取仓库状态",...items,"写入操作记录","任务执行完成"];
  return base.map((item,index)=>`<div class="batch-code-line ${index===base.length-1?"good":index===3?"command":""}"><span>${String(index+1).padStart(3,"0")}</span><span>${esc(item)}</span></div>`).join("");
}

function contentHtml(screen) {
  const title = esc(screen.title);
  const itemRows = rows(screen.items);
  const details = sideCards(screen.side);
  if (screen.layout === "editor") {
    return `<section class="batch-content batch-layout-editor"><div class="batch-panel focus"><div class="batch-panel-head"><b>${title}内容</b><span>编辑 · 预览</span></div><div class="batch-editor"><div class="batch-input">${esc(screen.items[0])}</div><div class="batch-editor-box"><div class="batch-editor-toolbar">编辑　预览　B　I　⌁　&lt;/&gt;　@</div><div class="batch-editor-body">${screen.items.slice(1).map((x,i)=>`${i?"":"## "}${esc(x)}<br><br>`).join("")}继续输入内容或拖入文件……</div></div></div><div class="batch-footer"><span>草稿已自动保存在本机</span><span>${esc(screen.primary)}</span></div></div><aside class="batch-panel"><div class="batch-panel-head"><b>发布与属性</b><span>恢复默认</span></div><div class="batch-scroll batch-detail">${details}</div><div class="batch-footer"><span>检查通过</span><span>设置完整</span></div></aside></section>`;
  }
  if (screen.layout === "console") {
    return `<section class="batch-content batch-layout-console"><aside class="batch-panel"><div class="batch-panel-head"><b>步骤与文件</b><span>${screen.items.length}</span></div><div class="batch-scroll">${itemRows}</div></aside><div class="batch-panel focus"><div class="batch-panel-head"><b>实时详情与日志</b><span>自动滚动</span></div><div class="batch-console">${consoleLines(screen.items)}</div><div class="batch-footer"><span>${esc(screen.status)}</span><span>下载日志</span></div></div></section>`;
  }
  if (screen.layout === "settings") {
    return `<section class="batch-content batch-layout-settings"><div class="batch-panel focus"><div class="batch-panel-head"><b>配置项</b><span>所有更改自动保存</span></div><div class="batch-scroll">${screen.items.map((item,index)=>`<div class="batch-setting"><div><b>${esc(item)}</b><p>${index%2?"继承全局默认，可单独覆盖":"当前设置已生效"}</p></div><span class="batch-toggle"></span></div>`).join("")}</div><div class="batch-footer"><span>最后更新：刚刚</span><span>${esc(screen.primary)}</span></div></div><aside class="batch-panel"><div class="batch-panel-head"><b>设置摘要</b><span>查看说明</span></div><div class="batch-scroll batch-detail">${details}</div></aside></section>`;
  }
  if (screen.layout === "canvas") {
    return `<section class="batch-content batch-layout-canvas"><div class="batch-panel focus"><div class="batch-panel-head"><b>${title}可视化画布</b><span>适配全部 · 100%</span></div><div class="batch-canvas"><div class="batch-lanes">${screen.items.slice(0,4).map((item,index)=>`<div class="batch-lane"><h3><span>${["来源","直接关系","间接关系","目标"][index]}</span><span>${index+2}</span></h3>${[item,screen.items[(index+1)%screen.items.length]].map(x=>`<div class="batch-node"><b>${esc(x)}</b><span>${esc(screen.module)} · 关系已验证</span></div>`).join("")}</div>`).join("")}</div></div><div class="batch-footer"><span>${esc(screen.status)}</span><span>拖动画布 · 滚轮缩放</span></div></div></section>`;
  }
  if (screen.layout === "timeline") {
    return `<section class="batch-content batch-layout-timeline"><div class="batch-panel focus"><div class="batch-panel-head"><b>${title}时间线</b><span>筛选与导出</span></div><div class="batch-timeline">${screen.items.map((item,index)=>`<div class="batch-event"><b>${esc(item)}</b><span>${index===0?"刚刚":`${index*2+1} 小时前`} · lele · 状态已记录</span></div>`).join("")}</div><div class="batch-footer"><span>${esc(screen.status)}</span><span>加载更早记录</span></div></div></section>`;
  }
  if (screen.layout === "wizard") {
    return `<section class="batch-content batch-layout-wizard"><div class="batch-panel focus"><div class="batch-panel-head"><b>${title}配置</b><span>步骤 2 / 3</span></div><div class="batch-scroll">${screen.items.map((item,index)=>`<div class="batch-setting"><div><b>${esc(item)}</b><p>${index===0?"已验证":"可以继续修改"}</p></div><span class="batch-row-tag">${index===0?"通过":"⌄"}</span></div>`).join("")}</div><div class="batch-footer"><span>返回上一步</span><span>${esc(screen.primary)}</span></div></div><aside class="batch-panel"><div class="batch-panel-head"><b>执行摘要</b><span>即时更新</span></div><div class="batch-scroll batch-detail">${details}</div></aside></section>`;
  }
  if (screen.layout === "state") {
    return `<section class="batch-content batch-layout-state"><div class="batch-panel focus"><div class="batch-panel-head"><b>${title}</b><span>统一状态规范</span></div><div class="batch-state-grid">${screen.items.map((item,index)=>`<article class="batch-state-card ${index%3===1?"warning":index%3===2?"danger":""}"><h3>${esc(item)}</h3><p>${esc(screen.side[index%screen.side.length])}。保留当前输入与上下文，并显示明确恢复路径。</p><span class="batch-state-action">${index%3===2?"确认影响":"查看解决方式"}</span></article>`).join("")}</div><div class="batch-footer"><span>${esc(screen.status)}</span><span>所有状态均可返回</span></div></div></section>`;
  }
  if (screen.layout === "dashboard") {
    return `<section class="batch-content batch-layout-dashboard"><div class="batch-panel focus"><div class="batch-panel-head"><b>核心数据与最近活动</b><span>查看全部</span></div><div class="batch-scroll">${itemRows}</div><div class="batch-footer"><span>按重要程度排序</span><span>打开完整视图</span></div></div><aside class="batch-panel"><div class="batch-panel-head"><b>状态摘要</b><span>实时</span></div><div class="batch-scroll batch-detail">${details}</div></aside></section>`;
  }
  return `<section class="batch-content batch-layout-list"><div class="batch-panel focus"><div class="batch-panel-head"><b>${title}列表</b><span>搜索 · 筛选 · 排序</span></div><div class="batch-scroll">${itemRows}</div><div class="batch-footer"><span>显示 ${screen.items.length} 项</span><span>加载更多</span></div></div><aside class="batch-panel"><div class="batch-panel-head"><b>所选详情</b><span>•••</span></div><div class="batch-scroll batch-detail"><h2>${esc(screen.items[0])}</h2><p>${esc(screen.subtitle)}</p>${details}</div><div class="batch-footer"><span>复制链接</span><span>${esc(screen.primary)}</span></div></aside></section>`;
}

function screenFragment(screen, includeCss = false) {
  return `${includeCss ? commonCss : ""}<article class="batch-entry" id="screen-${screen.no}">
  <div class="batch-page-meta"><span class="batch-page-index">页面 ${screen.no} / ${esc(screen.module)} · ${esc(screen.title)}</span><span class="batch-page-status">批量设计稿 V1 · ${layoutNames[screen.layout]} · 固定高度</span></div>
  <div class="batch-app"><div class="batch-titlebar"><div class="batch-traffic"><i></i><i></i><i></i></div><div class="batch-window-title">GitMate · ${esc(screen.module)} · ${esc(screen.title)}</div><div class="batch-tools"><span class="batch-tool">⌕</span><span class="batch-tool">⌘</span><span class="batch-tool">?</span></div></div>
  <div class="batch-body"><aside class="batch-sidebar"><div class="batch-brand"><span class="batch-avatar" aria-label="当前 GitHub 用户头像"></span><div><b>GitMate</b><span>lele · GitHub.com</span></div></div><div class="batch-repo"><span class="batch-repo-icon">GM</span><div><b>GitMate/mac-client</b><small>github.com · 私有</small></div><span>⌄</span></div>${navHtml(screen.nav)}<div class="batch-sidebar-bottom"><div class="batch-sync"><i></i><div><b>自动同步已开启</b><span>刚刚 · 2.4 GB</span></div></div><div class="batch-nav-item"><i>●</i><span>状态中心</span></div></div></aside>
  <main class="batch-main"><header class="batch-head"><div><h1>${esc(screen.title)}</h1><p>${esc(screen.subtitle)}</p></div><div class="batch-actions"><span class="batch-status"><i></i>${esc(screen.status)}</span><span class="batch-primary">${esc(screen.primary)}</span></div></header>${metrics(screen)}${contentHtml(screen)}</main></div></div></article>`;
}

const indexHtml = `<section class="batch-index"><h1>GitMate 剩余页面完整设计集</h1><p>第 30–91 页，共 ${screens.length} 张。项目模块已完整移除；所有页面采用白色高对比主题和固定软件高度。</p><div class="batch-index-grid">${screens.map(s=>`<a class="batch-index-card" href="#screen-${s.no}"><span>页面 ${s.no} · ${esc(s.module)}</span><b>${esc(s.title)}</b><small>${layoutNames[s.layout]}</small></a>`).join("")}</div></section>`;
const combined = `${commonCss}${indexHtml}${screens.map(s=>screenFragment(s,false)).join("\n")}`;

for (const dir of [canonicalDir, previewDir]) {
  fs.mkdirSync(dir, {recursive:true});
  for (const screen of screens) {
    const file = `page-${String(screen.no).padStart(2,"0")}-${screen.slug}-v1.html`;
    fs.writeFileSync(path.join(dir,file), screenFragment(screen,true), "utf8");
  }
  fs.writeFileSync(path.join(dir,"page-92-complete-design-batch-v1.html"), combined, "utf8");
}

console.log(`已生成 ${screens.length} 张独立设计稿和 1 份完整总览。`);
